name: Discord Notification on Merge

on:
  pull_request_target:
    types: [closed]

jobs:
  notify:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          REPOSITORY_NAME: ${{ github.repository }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_USER: ${{ github.event.pull_request.user.login }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{
                \"content\": null,
                \"embeds\": [
                  {
                    \"title\": \"${REPOSITORY_NAME}\",
                    \"description\": \"${PR_USER} の作成した Pull Request が ${{ github.event.pull_request.base.ref }} にマージされました 🎉 \n ${PR_TITLE}\",
                    \"color\": 5814783,
                    \"url\": \"${PR_URL}\",
                    \"author\": {
                      \"name\": \"${{ github.repository_owner }}\",
                      \"url\": \"https://github.com/${{ github.repository_owner }}\",
                      \"icon_url\": \"https://github.com/${{ github.repository_owner }}.png\"
                    }
                  }
                ],
                \"username\": \"GitHub CI/CD Bot\",
                \"avatar_url\": \"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png\"
              }" \
          $DISCORD_WEBHOOK_URL
